### ISSUE TITLE
File "source-template.tex" not found

### ISSUE THREAD

**Issue by tampueroc** [Template-Latex/Professional-CV#2]
Hola, descargando el zip desde https://latex.ppizarror.com/professional-cv, me arroja el siguiente error 
`File "source-template.tex" not found`
esto lo corregi editando el archivo "cv.tex", en la linea 38 a
`\input{source_template}`
`\input{template}`
Tal vez hay que corregir el archivo para descargar en el sitio.

**Comment by ppizarror** [comment]
Uf. Lo corregiré hoy mismo. Gracias por avisar

**Comment by ppizarror** [comment]
Corregido, nueva versión en línea :)
